### ISSUE TITLE
[Week 9] Project Milestone V1.2

### ISSUE THREAD

**Issue by ptvrajsk** [CS2103-AY1819S2-T12-4/main#109]
We are required to finish Milestone V1.2 this week. Please remember to close the issues regarding tasks/user stories once you have finished them.

# V1.2 Requirements
### User Guide
- [x] Remove Mockup, Replace with actual Screenshot.
- [x] Remove ``` Coming in V2.0 ``` tags.
- [x] Update feature changes accordingly.
***
### Developer Guide
- [x] Each user needs to describe the implementation of **AT LEAST 1** implementation that he/she has added. Expected length: 1+ Page. 
> The description can consider how the feature is implemented / why it is implemented that way / alternatives considered. The stated objective is to explain the implementation to a future developer, but a hidden objective is to show evidence that you can document deeply-technical content using prose, examples, diagrams, code snippets, etc. appropriately. To that end, you may also describe features that you plan to implement in the future, even beyond v1.4 (hypothetically).
***
### V1.2 Demo
- [x] Prepare 1 PC to show the Demo during class.
