### ISSUE TITLE
[Week 4] Project Milestone: mid-v1.0

### ISSUE THREAD

**Issue by WeiTangLau** [CS2103-AY1819S2-T12-4/main#56]
# Mid-v1.0
Based on the meeting on **31<sup>st</sup> January 2019**, we have decided to morph the project into **PDF++**.
 
### Establish a standardised workflow and environment to work on:
- [x] Git / ~~SourceTree~~
- [x] Setting up IDE & Github organisation

### Proper documentation for the list below:
- [x] User Stories
- [x] Target User Profile
- [x] Value Proposition of the project for the targeted user profile
- [x] Use cases
- [x] Non-functional Requirements
- [x] Glossary (if any)

**Comment by jetkan-yk** [comment]
## User stories
Based on the meeting on **7<sup>th</sup> February 2019**, we have brainstormed a list of user stories and classified them into 3 categories: **Must-have**, **Nice-to-have**, **Not-useful**.

Each user story is given a priority tag (i.e. **priority.High**, **priority.Medium**, **priority.Low**) which corresponds to its assigned category.

Here's the link to the [user stories](https://github.com/cs2103-ay1819s2-t12-4/main/projects/1).

**Comment by jetkan-yk** [comment]
## Non-functional requirements
Based on the meeting on **7<sup>th</sup> February 2019**, we have agreed upon the non-functional requirements of our product:

* **Technical requirements** 
The software should work on both 32-bit and 64-bit environments.

* **Platform compatibility** 
The software should work on Windows, Linux and OS-X platforms.

* **Response time** 
The software should respond within two seconds.

* **Cost** 
The software should be free of charge.

* **Privacy** 
The software should work entirely offline and should not collect user personal data for any purposes.

* **Licensing** 
The software is free, open-source does not require installation.

* **Portability**
The software should not require any installer, in other words, should be able to run without installing any additional softwares.

* **Extensibility** 
The software should take future growth into consideration e.g. adding features, carry-forward of customizations at next major version upgrade.

* **Testability**
The software should not have features that are hard to test both manual and automated testing.

* **Data requirements**
The data that is stored locally should be editable by user. In other words, expert users can open the file without using the application and edit it for his or her liking.

**Comment by ptvrajsk** [comment]
## Use Cases
Based on the meeting on **7th February 2019**, we have brainstormed the use cases of our product:
### Use Case 1
**System** : PDF++
**Actor** : Student
**Use Case** : UC1 - Viewing all PDFs within PDF++
**MSS** : 
````
1. On startup, application presents all tracked PDF files.
2. Student navigates through the list of PDFs using the mouse.
3. Use case ends.
````

Extension(s) :

 1. a. **User is unable to find the PDF in the full list.**
```    
1. Student types PDF name into search bar.
2. PDF Appears in view of user.
3. Continue to Step 2 of MSS.
```
### Use Case 2
**System** : PDF++
**Actor** : Student
**Use Case** : UC2 - Adding new PDF to PDF++
**MSS** : 
````
1. Student clicks the "+" button at the top left hand corner of the UI.
2. Student navigates to location of PDF on computer.
3. Student selects the PDF file and clicks "OK".
4. Use case ends.
````

### Use Case 3
**System** : PDF++
**Actor** : Student
**Use Case** : UC3 - Opening PDF from PDF++
**MSS** : 
````
1. Student double clicks the PDF of choice from the total list of PDFs.
2. Default PDF application in Student's computer opens the PDF File.
3. Use Case ends.
````
Extension(s) :

 2. a. **User does not have default PDF application set.**
```    
1. Operating system prompts user to select application to open the PDF.
2. User selects built in program (within the OS) to open the PDF.
3. Continue to Step 3 of MSS.
```

## Glossary
***NIL***

**Comment by lormee94** [comment]
## Target User Profile
University student (with a lot of reading material)

**Comment by lormee94** [comment]
## Value Proposition of the Product
Centralised management and overview of all PDFs, with additional chronological organisation and enhancements.
