### ISSUE TITLE
[Week 6] Project Milestone: Mid v1.1

### ISSUE THREAD

**Issue by WeiTangLau** [CS2103-AY1819S2-T12-4/main#58]
### Project Management
- [x] Organisation Set up
- [x] Repo Set up
- [x] Workflow

### Documentation
- [x] About us (Raj)
- [x] Contact us (Raj)
- [x] README.adoc (WeiTang)
- [x] User Guide (Jet)
- [x] Developer Guide (Jeremy)

### Product
Each member to do a local-impact change to the code

**Comment by ptvrajsk** [comment]
About Us & Contact Us has been complete and updated. Error in cloning caused the code to be directly merged to Organization Repo. However I've ensured that Travis builds and all automated tests are successfully run. Apologies for the inconvenience.

**Comment by WeiTangLau** [comment]
Refer to #53 for the PR created for README.adoc. I have created and linked the badges to the automated tester for our repo

**Comment by jetkan-yk** [comment]
UserGuide.adoc has been updated. Please refer to #50 for more details.

**Comment by lormee94** [comment]
Started to update on DeveloperGuide.adoc, refer to PR #51 for more details.

**Comment by ptvrajsk** [comment]
All PRs have been reviewed & merged.
Good job guys.

![Alt Text](https://media.giphy.com/media/BIuuwHRNKs15C/giphy.gif)


###### LATB
