### ISSUE TITLE
[Week 7] Project Milestone v1.1

### ISSUE THREAD

**Issue by WeiTangLau** [cs2103-ay1819s2-t12-4/main#59]
### Completed at least 60% of Milestone v1.1 completion
The requirement stated that at least 60% completion for Milestone v1.1. However, we should aim at least 80%
**Note: The project progress are tracked automatically, so do follow the instructions closely**

### Summary of Milestone v1.1
Milestone | Work to be done
----|----
Team Organisation / Repo | [Refer to website](https://github.com/cs2103-ay1819s2-t12-4/main/issues)
Code enhancement | created PRs to do local/global changes
Photo uploaded | Compliance with the [guideline]()
Project docs updated | updated docs are merged to master branch
Milestone wrapped up | a commit in master branch tagged as v1.1

**Note: Remember to tag the commit as v1.1**

#### v1.1 Documentation
Update 
- [ ] User Guide
- [ ] README
- [ ] About Us pages 
- [ ] Update Developer Guide 
**Submission: Merge your changes to the master branch of your repo. Create a PR with your changes.**

#### v1.1 Product
- [ ] Each member to add some enhancements (local & global impact enhancements) in line with vision for v2.0 (Check the Milestone v1.1 for enhancements)
